[tool.poetry]
name = "nandu"
version = "0.1.0"
description = "OGC API - Processes example with pygeoapi"
authors = ["Carsten Ehbrecht <ehbrecht@dkrz.de>"]

[tool.poetry.dependencies]
python = ">=3.10"
pygeoapi = ">=0.18.0"
flask = "<3.0.0"

[tool.poetry.group.dev.dependencies]
pytest = ">=8.3.4"
ruff = ">=0.8.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 150

